config/routes.rb
Template::Application.routes.draw do
  resources :examples

  root :to => "examples#index"

end

app/models/example.rb
class Example < ActiveRecord::Base
  attr_accessible :starting_point, :available_functions, :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/examples_controller.rb
class ExamplesController < ApplicationController
  layout "examples"



  # GET /examples
  # GET /examples.json
  def index
    @examples = Example.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @examples }
    end
  end

  # GET /examples/1
  # GET /examples/1.json
  def show
    @example = Example.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @example }
    end
  end

  # GET /examples/new
  # GET /examples/new.json
  def new
    @example = Example.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @example }
    end
  end

  # GET /examples/1/edit
  def edit
    @example = Example.find(params[:id])
  end

  # POST /examples
  # POST /examples.json
  def create
    @example = Example.new(params[:example])

    respond_to do |format|
      if @example.save
        format.html { redirect_to @example, notice: 'Example was successfully created.' }
        format.json { render json: @example, status: :created, location: @example }
      else
        format.html { render action: "new" }
        format.json { render json: @example.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /examples/1
  # PUT /examples/1.json
  def update
    @example = Example.find(params[:id])

    respond_to do |format|
      if @example.update_attributes(params[:example])
        format.html { redirect_to @example, notice: 'Example was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @example.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /examples/1
  # DELETE /examples/1.json
  def destroy
    @example = Example.find(params[:id])
    @example.destroy

    respond_to do |format|
      format.html { redirect_to examples_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/examples_helper.rb
module ExamplesHelper
end

app/views/examples/_form.html.erb
<%= form_for(@example) do |f| %>
  <% if @example.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@example.errors.count, "error") %> prohibited this example from being saved:</h2>

      <ul>
      <% @example.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container-fluid">
    <div class="row-fluid">
      <div class="field span2">
        <%= f.label :title %>
        <%= f.text_field :title %>
      </div>
    </div>
    <div class="row-fluid">
      <div class="field span2">
        <%= f.label :starting_point %>
        <%= f.text_area :starting_point %>
      </div>
       <div class="field span2">
        <%= f.label :available_functions %>
        <%= f.text_area :available_functions %>
      </div>
</div>
      <div class="row-fluid">
       <div class="actions span2">
        <%= f.submit %>
      </div>
      </div>
    
  </div>
<% end %>

app/views/examples/edit.html.erb
<h1>Editing example</h1>

<%= render 'form' %>

<%= link_to 'Show', @example %> |
<%= link_to 'Back', examples_path %>

app/views/examples/index.html.erb
<div class="container">
  <h1>Examples</h1>
    <div class="row">
      <div class="span6">

        <table class="table table-bordered">
        <tr>
          <th>Title</th>
        </tr>

      <% @examples.each do |example| %>
        <tr>
          <td><%= example.title %></td>
          <td><%= link_to 'GoTo', example %></td>
          <!--<td><%= link_to 'Edit', edit_example_path(example) %></td>
          <td><%= link_to 'Destroy', example, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
        </tr>
      <% end %>
      </table>

      <br />

      <%= link_to 'New Example', new_example_path %>
    </div>
  </div>
</div>

app/views/examples/new.html.erb
<%= render 'form' %>

app/views/examples/show.html.erb
<script>
	function run_js(){

		try{
		  eval($('#content').val());
		  $('#codeLabel').removeClass('label-important');
		  $('#codeLabel').addClass('label-success');
		  $('#codeLabel').text('Success');
		}catch(err){
			$('#codeLabel').removeClass('label-success');
			$('#codeLabel').addClass('label-important');
			$('#codeLabel').text('Error in code');
		}
	}

	function clear_results(){
		$('#codeLabel').removeClass();
		$('#codeLabel').addClass('label');
		$('#codeLabel').text('Base Code');
		$('#Results').empty();
	}
</script>

<div class="container-fluid">
	<div id="top-section" class="row-fluid" style="height: 400px">
		<div class="span12">
			<div class="row-fluid">
				<div class="span7">
					<span id="codeLabel" class="label">Base Code</span>
				</div>
				<div class="span5">
					<span id="codeLabel" class="label">Helpers</span>
				</div>
			</div>
			<div id="helper" class="row-fluid" >
			     <!--Body content-->
			     <div  id="helper2" class="span7">
			     	<textarea style="resize: none;height: 400px;" class="span12" id="content" placeholder="Type Here" ><%= @example.starting_point %></textarea>
			     </div>
		  
				 <div class="span5 ">
			     	<textarea style="resize: none;height: 400px;" class="span12 well" id="right-bar" readonly="readonly"  ><%=@example.available_functions%></textarea>
			     </div>
	    	</div>
	    	<div class="row-fluid">
				<button onClick="run_js()" class="btn btn-info">Execute</button>
				<button onClick="clear_results()" class="btn btn-danger">Clear</button>
			</div>
		</div>	
	</div>

	<div id="bottom-section" >
		<div class="row-fluid">
			<div class="span12 ">
				&nbsp;
			</div>
		</div>
		<div class="row-fluid">
			<div class="span12 ">
				<span id="codeLabel" class="label">Results</span>
			</div>
		</div>
    	<div class="row-fluid">
			<div class="span12">
				<textarea readonly="readonly" class="span12 well" id="Results" style="height: 150px;resize: none; font-size: 12px"></textarea>
			</div>
		</div>
	</div>
	
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Template</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">
    <%= yield %>
  </div>
  
</body>
</html>

app/views/layouts/examples.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Template</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar">
  		<div class="navbar-inner">
      <a class="brand" href="/examples"><i class="icon-eject"></i></a>
			<ul class="nav">
          <% @examples =  @examples = Example.all%>

          <% @examples.each do |example| %>


            <li><%= link_to example.title, :controller => "examples", :action => "show", :id => example.id %></li>
          <% end %>
    		</ul>
  		</div>
	</div>
<%= yield %>

</body>
</html>